# Example Keisei DRL Shogi configuration (YAML)
env:
  seed: 42
  device: "cpu"
  input_channels: 46
  max_moves_per_game: 256
training:
  learning_rate: 0.0003
  gamma: 0.99
  clip_epsilon: 0.2
  ppo_epochs: 4
  minibatch_size: 64
  value_loss_coeff: 0.5
  entropy_coef: 0.01
  steps_per_epoch: 2048
  total_timesteps: 100000
  checkpoint_interval_timesteps: 10000
evaluation:
  enable_periodic_evaluation: true
  evaluation_interval_timesteps: 50000
  num_games: 20
  opponent_type: "random"
  max_moves_per_game: 256
  log_file_path_eval: "eval_log.txt"
  wandb_log_eval: false
logging:
  model_dir: "models"
  log_file: "train.log"
wandb:
  enabled: false
  project: "keisei-shogi"
  entity: null
demo:
  enable_demo_mode: true  # If true, enables demo mode with per-move delay and extra logging
  demo_mode_delay: 0.5     # Delay in seconds between moves in demo mode
