[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "keisei"
version = "0.1.0"
description = "DRL Shogi Client: Deep Reinforcement Learning for Shogi using PPO"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "torch>=1.10",
    "numpy",
    "pytest",
    "black",
    "flake8"
]

[tool.setuptools.packages.find]
where = ["keisei"]
