[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "keisei"
version = "0.1.0"
description = "DRL Shogi Client: Deep Reinforcement Learning for Shogi using PPO"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "torch",
    "numpy",
    "python-dotenv",
    "wandb", # wandb will pull in its own dependencies like GitPython, pydantic, sentry-sdk, setproctitle
    "requests",     # Keeping for now, pending user clarification
    # "setproctitle", # Removed, will be installed as a wandb dependency
    # "GitPython",    # Removed, will be installed as a wandb dependency
    # "pydantic",     # Removed, will be installed as a wandb dependency
    # "sentry-sdk",   # Removed, will be installed as a wandb dependency
    # "Jinja2", # Kept removed
    # "MarkupSafe", # Kept removed
    # "networkx", # Kept removed
    # "sympy", # Kept removed
    # "triton", # Kept removed
    # matplotlib was in dependencies but seems more like a dev/visualization tool
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-pylint",
    "black==25.1.0", # Updated to version from requirements-dev.txt
    "matplotlib", # Moved from core dependencies
    "pylint",
    "mypy",
    "isort",
    "annotated-types==0.7.0",
    "astroid==3.3.10",
    "coverage==7.8.0",
    "dill==0.4.0",
    "filelock==3.18.0",
    "flake8==7.2.0",
    "fsspec==2025.3.2",
    "idna==3.10",
    "iniconfig==2.1.0",
    "mccabe==0.7.0",
    "mpmath==1.3.0",
    "mypy_extensions==1.1.0",
    "packaging==25.0",
    "pathspec==0.12.1",
    "platformdirs==4.3.8",
    "pluggy==1.6.0",
    "protobuf==6.31.0", # Consider if this is truly dev-only
    "psutil==7.0.0",
    "pycodestyle==2.13.0",
    "pydantic_core==2.33.2",
    "pyflakes==3.3.2",
    "pytest-cov==6.1.1",
    "PyYAML==6.0.2",
    "smmap==5.0.2",
    "tomlkit==0.13.2",
    "typing-inspection==0.4.0",
    "typing_extensions==4.13.2",
    "deptry", # Added deptry
]

[tool.setuptools.packages.find]
where = ["keisei"]

[pytest]
addopts = --pylint

[tool.pylint.messages_control]
disable = "redefined-outer-name"

[tool.mypy]
check_untyped_defs = true

[tool.flake8]
exclude = [
    ".git",
    "__pycache__",
    "env",
    "venv",
    ".tox",
    ".eggs",
    "*.egg-info"
]
max-line-length = 120
extend-ignore = "E203"