[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "keisei"
version = "0.1.0"
description = "DRL Shogi Client: Deep Reinforcement Learning for Shogi using PPO"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "torch==2.0.1",
    "numpy==1.24.3",
    "pytest==7.4.0",
    "pytest-pylint",
    "black==23.7.0",
    "tensorboard==2.13.0",
    "matplotlib==3.7.2",
    "pylint==2.17.5",
    "mypy==1.5.1",
    "isort==5.12.0",
    "shogi-engine==0.0.5",
]

[tool.setuptools.packages.find]
where = ["keisei"]

[tool.pylint.messages_control]
disable = "redefined-outer-name"

[tool.mypy]
check_untyped_defs = true

[tool.flake8]
exclude = [
    ".git",
    "__pycache__",
    "env",
    "venv",
    ".tox",
    ".eggs",
    "*.egg-info"
]
max-line-length = 120
extend-ignore = "E203"  # Optional: if you use black, this avoids conflicts
