name: 'Setup Project Environment'
description: 'Sets up Python, caches dependencies, and installs project requirements'
runs:
  using: "composite"
  steps:
    - name: Set up Python 3.12
      uses: actions/setup-python@v4 # Updated to v4
      with:
        python-version: 3.12
      shell: bash # Explicitly set shell for consistency if needed later

    - name: Cache pip dependencies
      uses: actions/cache@v4 # Updated to v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
      shell: bash

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Conditionally install dev requirements if the file exists
        if [ -f requirements-dev.txt ]; then
          pip install -r requirements-dev.txt
        fi
        pip install -e .
      shell: bash
